# Nombre descriptivo para el flujo de trabajo
name: Build and Deploy .NET Function App

on:
  # Se activa cada vez que haces un push a la rama 'master'
  push:
    branches:
      - master
  # También permite la ejecución manual desde la pestaña Actions en GitHub
  workflow_dispatch:

# Variables de entorno para mantener el código limpio y fácil de mantener
env:
  AZURE_FUNCTIONAPP_NAME: 'AoristoTowersFunctions' # El nombre EXACTO de tu Function App en Azure
  # --- CAMBIO CLAVE: Apuntamos directamente al archivo .csproj ---
  PROJECT_PATH: 'AoristoTowersFunctions/AoristoTowersFunctions.csproj'
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup .NET SDK'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # --- CORRECCIÓN: Restauramos solo las dependencias del proyecto de Functions ---
      - name: 'Restore NuGet packages'
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      # --- CORRECCIÓN: Compilamos solo el proyecto de Functions ---
      - name: 'Build Function App project'
        run: dotnet build "${{ env.PROJECT_PATH }}" --configuration Release --no-restore

      - name: 'Publish the Function App project'
        run: dotnet publish "${{ env.PROJECT_PATH }}" --configuration Release --no-build --output ./publish

      - name: 'Upload artifact for deployment job'
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy.outputs.webapp-url }}
    
    steps:
      - name: 'Download artifact from build job'
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: 'Azure Login'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AoristoTowersFunctions_SPN }}
      
      - name: 'Deploy to Azure Functions'
        id: deploy
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '.'
