name: Build and Deploy .NET Function App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'AoristoTowersFunctions' # El nombre EXACTO de tu Function App en Azure
  PROJECT_PATH: 'AoristoTowersFunctions/AoristoTowersFunctions.csproj' # Ruta directa al archivo de proyecto
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 'Production' # Puedes definir un entorno para gestionar secretos si lo deseas

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup .NET SDK'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Restore, Build, and Publish'
        run: dotnet publish "${{ env.PROJECT_PATH }}" --configuration Release --output ./publish
        # Este comando hace todo en un paso y coloca el resultado en una carpeta 'publish' en la raíz.

      - name: 'Azure Login'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AoristoTowersFunctions_SPN }}

      - name: 'Deploy to Azure Functions'
        id: deploy
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ./publish # Despliega el contenido de la carpeta 'publish'
